// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0RbOyJaIHmYbyg5B6giLyCmu-GxxnM44',
    appId: '1:632583053750:web:14820a5f52edc23b446117',
    messagingSenderId: '632583053750',
    projectId: 'jobtodo-48aff',
    authDomain: 'jobtodo-48aff.firebaseapp.com',
    storageBucket: 'jobtodo-48aff.appspot.com',
    measurementId: 'G-Q46QJ0NTJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGOO4r8IiW_hldHg4H3YPLZ1rZhuSZsBc',
    appId: '1:632583053750:android:f8c4145aa05a4c85446117',
    messagingSenderId: '632583053750',
    projectId: 'jobtodo-48aff',
    storageBucket: 'jobtodo-48aff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpPhvFUjzLb5BTIaUPkyyVJ9RKzVybx-Y',
    appId: '1:632583053750:ios:2b6bd9d8a737bc34446117',
    messagingSenderId: '632583053750',
    projectId: 'jobtodo-48aff',
    storageBucket: 'jobtodo-48aff.appspot.com',
    androidClientId: '632583053750-4j6tr6upn1r1nbjsc4jrs7vrqffb71c5.apps.googleusercontent.com',
    iosClientId: '632583053750-bkdp379k7m43mnefbpudjbv2ckj2f1bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobappv2',
  );
}
